name: family_health_organization
version: 1.0.0+1
description: A Flutter app for Family Health Organization
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  http: ^1.0.0
  shared_preferences: ^2.0.15
  qr_flutter: ^4.1.0
  flutter_lints: ^2.0.0
  go_router: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

 
